'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnnualFees_Default

    '''<summary>
    '''CaptchaUpdateProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaptchaUpdateProgress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlFeeYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFeeYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''linkInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkInvoice As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UserTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserTabs As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tabWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabWelcome As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''btnBeginFeeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBeginFeeReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDeadline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeadline As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pIncorrectClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pIncorrectClass As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''feeRatesSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feeRatesSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tabHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabHistory As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''hlPermitFees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPermitFees As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''grdFeeHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFeeHistory As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabFeeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabFeeCalculation As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''pnlFeeContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFeeContact As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlFeeContactInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFeeContactInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hlContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlContacts As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pContactInfoMissing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pContactInfoMissing As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pFinalSubmitError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pFinalSubmitError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnVerifyContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerifyContact As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlFeeCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFeeCalculation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCurrentClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentClass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClass As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlEmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmissions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''txtVOCTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVOCTons As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvtxtVOCTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvtxtVOCTons As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rnvtxtVOCTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnvtxtVOCTons As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblVOCFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVOCFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNOxTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOxTons As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvtxtNOxTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvtxtNOxTons As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rnvtxtNOxTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnvtxtNOxTons As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblNOxFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOxFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPMTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPMTons As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvtxtPMTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvtxtPMTons As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rnvtxtPMTons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnvtxtPMTons As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblPMFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPMFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSO2Tons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSO2Tons As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvtxtSO2Tons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvtxtSO2Tons As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rnvtxtSO2Tons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnvtxtSO2Tons As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblSO2Fee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO2Fee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmissionsTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmissionsTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmissionFeeTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmissionFeeTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RegsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegsChecklist As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkPart70Source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPart70Source As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSmSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSmSource As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblpart70SMFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpart70SMFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPart70MaintenanceFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPart70MaintenanceFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkNSPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNSPS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNSPS1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNSPS1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblNspsRemovalNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNspsRemovalNotice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkNSPSExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNSPSExempt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pNspsExemptionWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNspsExemptionWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NspsExemptionsChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NspsExemptionsChecklist As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lblNSPSFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNSPSFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalFee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdminFeeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminFeeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdminFeeAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminFeeAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaveFeeCalcMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveFeeCalcMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCancelFeeCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelFeeCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSavePnlFeeCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePnlFeeCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlFeeSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFeeSignature As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ValidationSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''txtPayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPayType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblPaymentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblPaymentType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbladminfeeSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbladminfeeSign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdminfeeamtSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdminfeeamtSign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwner As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOwner As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtOwnerTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnerTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvOwnerTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOwnerTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCancelSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSignature As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSavepnlSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavepnlSign As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlFeeSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFeeSubmit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnCancelSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.MainLayout
        Get
            Return CType(MyBase.Master, GECO.MainLayout)
        End Get
    End Property
End Class
