<%@ Page Language="VB" MasterPageFile="~/Main.master" AutoEventWireup="false" Inherits="GECO.FacilityAdmin" Title="GECO Facility Admin" CodeBehind="Admin.aspx.vb" %>

<%@ MasterType VirtualPath="~/Main.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Content" runat="Server">
    <h1>Facility Admin</h1>

    <p>
        <b>
            <asp:Label ID="lblFacilityDisplay" runat="server"></asp:Label></b>
        <br />
        AIRS Number:
       
        <asp:Label ID="lblAIRS" runat="server"></asp:Label>
    </p>

    <ul class="menu-list-horizontal">
        <li>
            <asp:HyperLink ID="lnkFacilityHome" runat="server" NavigateUrl="~/Facility/">Menu</asp:HyperLink>
        </li>
        <li>
            <asp:HyperLink ID="lnkFacilityInfo" runat="server" NavigateUrl="~/Facility/Summary.aspx">Facility Info</asp:HyperLink>
        </li>
        <li>
            <asp:HyperLink ID="lnkFacilityAdmin" runat="server" NavigateUrl="~/Facility/Admin.aspx" Enabled="false" CssClass="selected-menu-item disabled">User Access</asp:HyperLink>
        </li>
    </ul>

    <asp:UpdatePanel ID="FacilityAccessUpdatePanel" runat="server">
        <ContentTemplate>

            <p>The following users have access rights to this facility in GECO.</p>

            <% If UserIsAdmin %>
            <p>
                To change which section a user can access, use the "Edit" button next to their name. 
                To remove all access for a user, use the "Delete" button.
            </p>
            <% End If %>

            <asp:GridView ID="grdUsers" runat="Server" DataKeyNames="NUMUSERID" CssClass="table-simple table-checkbox-menu"
                AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="false">
                <Columns>
                    <asp:TemplateField ShowHeader="false">
                        <ItemTemplate>
                            <asp:LinkButton ID="DeleteButton" runat="server" CausesValidation="False" CommandName="Delete"
                                OnClientClick="return confirm('Are you sure you want to remove this user?');" Text="Delete" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="NUMUSERID" Visible="False" />
                    <asp:TemplateField HeaderText="User">
                        <ItemTemplate>
                            <%#Eval("FirstName") %> <%#Eval("LastName") %><br />
                            <%#Eval("Email") %>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:CheckBoxField HeaderText="Admin Rights" DataField="intAdminAccess" Text="&nbsp;">
                        <ItemStyle HorizontalAlign="Center" CssClass="table-cell-checkbox" />
                    </asp:CheckBoxField>
                    <asp:CheckBoxField HeaderText="Permit Fees" DataField="intFeeAccess" Text="&nbsp;">
                        <ItemStyle HorizontalAlign="Center" CssClass="table-cell-checkbox" />
                    </asp:CheckBoxField>
                    <asp:CheckBoxField HeaderText="Emissions Inventory" DataField="intEIAccess" Text="&nbsp;">
                        <ItemStyle HorizontalAlign="Center" CssClass="table-cell-checkbox" />
                    </asp:CheckBoxField>
                    <asp:CheckBoxField HeaderText="Emissions Statement" DataField="intESAccess" Text="&nbsp;">
                        <ItemStyle HorizontalAlign="Center" CssClass="table-cell-checkbox" />
                    </asp:CheckBoxField>
                </Columns>
                <EditRowStyle BackColor="#C0FFC0" BorderColor="Green" BorderStyle="Ridge" />
                <RowStyle BackColor="#ffffff" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#008A8C" BorderColor="Red" Font-Bold="True" ForeColor="White" />
                <HeaderStyle CssClass="table-head" />
                <AlternatingRowStyle BackColor="#f3f3f7" />
            </asp:GridView>
            <br />

            <asp:Panel runat="server" ID="pnlAddNewUser">
                <h3>Add New User</h3>
                <p>
                    To grant another user access to this facility, enter their email below. 
                    Note: They must already have a GECO account before they can be added here.

                </p>
                <p>
                    User Email:
                    <asp:TextBox ID="txtEmail" runat="server" ValidationGroup="NewUser" />
                    <asp:Button ID="btnAddUser" runat="server" Text="Add New User" ValidationGroup="NewUser" />
                    <asp:RequiredFieldValidator ID="rfvEmail" runat="server" ControlToValidate="txtEmail"
                        ErrorMessage="Valid email address is required." ValidationGroup="NewUser" />
                </p>
                <asp:Label ID="lblMessage" runat="server" ForeColor="#C00000" Visible="False" />
            </asp:Panel>

            <asp:UpdateProgress ID="UpdateProgress1" runat="server" DisplayAfter="0">
                <ProgressTemplate>
                    <div id="progressBackgroundFilter"></div>
                    <div id="progressMessage">
                        Please Wait...                       
                        <br />
                        <img alt="Loading" src="<%= Page.ResolveUrl("~/assets/images/progressbar_green.gif") %>" />
                    </div>
                </ProgressTemplate>
            </asp:UpdateProgress>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
