'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FacilityContacts

    '''<summary>
    '''lnkFacilityHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFacilityHome As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lnkFacilityInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFacilityInfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lnkFacilityAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFacilityAdmin As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lnkFacilityContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFacilityContacts As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litPermitFeeCommPref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPermitFeeCommPref As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litPermitFeeContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPermitFeeContact As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litPermitAppsCommPref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPermitAppsCommPref As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litPermitAppsContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPermitAppsContact As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEICommPref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEICommPref As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEIContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEIContact As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.MainLayout
        Get
            Return CType(MyBase.Master, GECO.MainLayout)
        End Get
    End Property
End Class
