'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetCommunicationPreferences

    '''<summary>
    '''settings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents settings As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pNotSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNotSelected As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbCommPref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCommPref As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pPrefSaveError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pPrefSaveError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSavePref control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePref As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidAirs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAirs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.MainLayout
        Get
            Return CType(MyBase.Master, GECO.MainLayout)
        End Get
    End Property
End Class
