'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eis_eucontrolapproach_edit
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''btnSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummary As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sumvUnitCPEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumvUnitCPEdit As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''lblEmissionUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmissionUnitID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEmissionUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmissionUnitID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmissionUnitDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmissionUnitDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEmissionUnitDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmissionUnitDesc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblControlApproachDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlApproachDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtControlApproachDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtControlApproachDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvControlApproachDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvControlApproachDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblPctCtrlApproachCapEffic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPctCtrlApproachCapEffic As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPctCtrlApproachCapEffic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPctCtrlApproachCapEffic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvPctCtrlApproachCapEffic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvPctCtrlApproachCapEffic As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''filtxtPctCtrlApproachCapEffic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtPctCtrlApproachCapEffic As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''rngvPctCtrlApproachCapEffic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvPctCtrlApproachCapEffic As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblPctCtrlApproachEffect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPctCtrlApproachEffect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPctCtrlApproachEffect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPctCtrlApproachEffect As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvPctCtrlApproachEffect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvPctCtrlApproachEffect As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''filtxtPctCtrlApproachEffect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtPctCtrlApproachEffect As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''rngvPctCtrlApproachEffect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvPctCtrlApproachEffect As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblControlApproachComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlApproachComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtControlApproachComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtControlApproachComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regexpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexpName As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEUControlMeasureWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEUControlMeasureWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sumvControlMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumvControlMeasure As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''gvwEUControlMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwEUControlMeasure As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblddlcontrolmeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblddlcontrolmeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlControlMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlControlMeasure As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvControlMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvControlMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnAddControlMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddControlMeasure As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEUControlPollutantWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEUControlPollutantWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sumvCMReductionEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumvCMReductionEff As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''sumvPollutantDGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumvPollutantDGV As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''gvwEUControlPollutant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwEUControlPollutant As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblControlpollutants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlpollutants As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlControlPollutants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlControlPollutants As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvddlControlPollutants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvddlControlPollutants As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCMReductionEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCMReductionEff As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCMReductionEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCMReductionEff As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rqvCMReductionEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqvCMReductionEff As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''filtxtCMReductionEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtCMReductionEff As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''rngvCMReductionEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvCMReductionEff As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''btnAddControlPollutant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddControlPollutant As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblSeparatorOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparatorOnly As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReturnSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnSummary2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDelete As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlDeleteUnitCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDeleteUnitCA As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDeleteUnitCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteUnitCA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteDetails As Global.System.Web.UI.WebControls.Button
End Class
