'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eis_facility_details
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''btnEditAllInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditAllInfo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblSeparator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRequest As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFacilitySiteName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFacilitySiteName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLocationAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLocationAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocationAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocationAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblSupplementalLocationText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSupplementalLocationText2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSupplementalLocationText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSupplementalLocationText2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLocalityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocalityName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocalityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocalityName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLocationAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLocationAddressStateCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocationAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocationAddressStateCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLocationAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationAddressPostalCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocationAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocationAddressPostalCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMailingAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtmailingAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmailingAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSupplementalAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplementalAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSupplementalAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSupplementalAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressCityName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressCityName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressStateCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressStateCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressPostalCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMailingAddressPostalCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblMailingAddressComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMailingAddressComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtMailingAddressComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMailingAddressComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastEISSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastEISSubmit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdated As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnEditFacilityDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditFacilityDescription As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFacilitySiteDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFacilitySiteStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteStatusCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFacilitySiteStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteStatusCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblStatusCodeNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusCodeNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNAICSCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNAICSCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblFacilitySiteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFacilitySiteComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtFacilitySiteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFacilitySiteComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmit_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmit_M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastEISSubmit_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastEISSubmit_M As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdate_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate_M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtlastUpdate_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastUpdate_M As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnEditGeoInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditGeoInfo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLatitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLatitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLongitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLongitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkGoogleMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGoogleMap As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''imgGoogleStaticMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGoogleStaticMap As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''pnlLocationMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocationMap As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorCollectionMetCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorCollectionMetCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorReferenceDatCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorReferenceDatCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblGeographicComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGeographicComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastSubmitEPA_GC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastSubmitEPA_GC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastSubmitEPA_GC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastSubmitEPA_GC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdate_GC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate_GC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate_GC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate_GC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnEditContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditContact As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblNamePrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNamePrefix As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNamePrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamePrefix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblfirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfirstname As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtfirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfirstname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblIndividualTitleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndividualTitleText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtIndividualTitleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIndividualTitleText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressText_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressText_contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressText_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressText_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSupplementalAddressText_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplementalAddressText_contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSupplementalAddressText_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplementalAddressText_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressCityName_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressCityName_contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressCityName_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressCityName_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressStateCode_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressStateCode_contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressStateCode_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressStateCode_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressPostalCode_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressPostalCode_Contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTelephoneNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNumberText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumberText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''meeTelephoneNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meeTelephoneNumberText As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''txtTelephoneExtensionNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneExtensionNumberText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTelephoneNumberText_mobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNumberText_mobile As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneNumber_Mobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumber_Mobile As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''meeTelephoneNumber_Mobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meeTelephoneNumber_Mobile As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''lblTelephoneNumberText_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNumberText_fax As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneNumber_Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumber_Fax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''meeTelephoneNumber_Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meeTelephoneNumber_Fax As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''lblElectronicAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElectronicAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtElectronicAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtElectronicAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblAddressComment_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddressComment_contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAddressComment_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressComment_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmitEPA_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmitEPA_C As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastEISSubmitEPA_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastEISSubmitEPA_C As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdate_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate_C As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate_C As Global.System.Web.UI.WebControls.TextBox
End Class
