'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eis_fugitive_details
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''btnReturntoSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturntoSummary As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFugitiveStacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFugitiveStacks As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAddFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFugitiveRP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddFugitiveRP_ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFugitiveRP_ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''btnDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplicate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDuplicate_ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplicate_ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblReleasePointID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReleasePointID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtReleasePointID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReleasePointID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPStatusCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPStatusCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPFenceLineDistanceMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPFenceLineDistanceMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPFenceLineDistanceMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPFenceLineDistanceMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPFugitiveHeightMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPFugitiveHeightMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPFugitiveHeightMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPFugitiveHeightMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPFugitiveWidthMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPFugitiveWidthMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPFugitiveWidthMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPFugitiveWidthMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPFugitiveLengthMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPFugitiveLengthMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPFugitiveLengthMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPFugitiveLengthMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPFugitiveAngleMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPFugitiveAngleMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPFugitiveAngleMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPFugitiveAngleMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastEISSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastEISSubmit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdated As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNoRPGeoCoordInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRPGeoCoordInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLatitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLatitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLongitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLongitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlLocationMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocationMap As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgGoogleStaticMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGoogleStaticMap As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''LblHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorCollectionMetCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorCollectionMetCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorReferenceDatCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorReferenceDatCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblGeographicComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGeographicComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmit_FGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmit_FGC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastEISSubmit_FGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastEISSubmit_FGC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdate_FGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate_FGC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate_FGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate_FGC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReleasePointAppMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReleasePointAppMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRPShutdownMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPShutdownMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvwRPApportionment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwRPApportionment As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceRPApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRPApp As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblSeparatorOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparatorOnly As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummary2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlPopUpAddFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopUpAddFugitiveRP As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewFugitiveRP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtNewFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtNewFugitiveRP As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''cusvFugitiveID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusvFugitiveID As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''reqvNewFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNewFugitiveRP As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtNewFugitiveRPDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewFugitiveRPDesc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvNewFugitiveRPDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNewFugitiveRPDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnInsertFugitiveID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertFugitiveID As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelFugitiveRP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDuplicate As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDupFugitiveID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDupFugitiveID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDupFugitiveID_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDupFugitiveID_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''cusvDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusvDuplicate As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''reqvDupEUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvDupEUID As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDupFugitiveDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDupFugitiveDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvDupFugitiveDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvDupFugitiveDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDupInsertFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDupInsertFugitiveRP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelDupFugitiveRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDupFugitiveRP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hiddenFacilityLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenFacilityLatitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hiddenFacilityLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenFacilityLongitude As Global.System.Web.UI.WebControls.HiddenField
End Class
