'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EIS_report_processes
    
    '''<summary>
    '''btnReportsHome_Processes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReportsHome_Processes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFacilitySiteID_Processes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteID_Processes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFacilitySiteID_Processes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteID_Processes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFacilityName_Processes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilityName_Processes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFacilityName_Processes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilityName_Processes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnExport_Processes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport_Processes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblEmptygvwProcesses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmptygvwProcesses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvwProcesses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwProcesses As Global.System.Web.UI.WebControls.GridView
End Class
