'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EIS_rp_entry
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ModalUpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalUpdateProgress1 As Global.AjaxControls.ModalUpdateProgress
    
    '''<summary>
    '''pnlFacilityEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFacilityEdit As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''lblFacilitySiteName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFacilitySiteName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLocationAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLocationAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocationAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocationAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblSupplementalLocationText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSupplementalLocationText2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSupplementalLocationText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSupplementalLocationText2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLocalityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocalityName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocalityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocalityName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLocationAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLocationAddressStateCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocationAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocationAddressStateCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLocationAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationAddressPostalCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLocationAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLocationAddressPostalCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMailingAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvMailingAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressText As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSupplementalAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplementalAddressText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtSupplementalAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSupplementalAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbwSupplementalAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbwSupplementalAddressText As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''lblMailingAddressCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressCityName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressCityName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvMailingAddressCityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressCityName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMailingAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressStateCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFacility_StateMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFacility_StateMail As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvMailingAddressStateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressStateCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressPostalCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressPostalCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressPostalCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rgxvMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgxvMailingAddressPostalCode As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''filttxtMailingAddressPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filttxtMailingAddressPostalCode As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''LblMailingAddressComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMailingAddressComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtMailingAddressComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMailingAddressComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFacilitySiteDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvFacilitySiteDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNAICSCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNAICSCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mpeNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeNAICSCode As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNAICSCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rgxvNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgxvNAICSCode As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''cusvNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusvNAICSCode As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''btnNAICSLoopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNAICSLoopup As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFacilitySiteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFacilitySiteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regexpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexpName As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''upLatLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upLatLon As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LblLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLatitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLatitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtLatitudeMeasure As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvLatitudeMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvLatitudeMeasure As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''LblLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLongitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLongitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtLongitudeMeasure As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvLongitudeMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvLongitudeMeasure As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lnkGoogleMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGoogleMap As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''imgGoogleStaticMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGoogleStaticMap As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''pnlLocationMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocationMap As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbtnGetLatLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnGetLatLon As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LblHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorCollectionMetCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHorCollectionMetCode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHorCollectionMetCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LblHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtHorizontalAccuracyMeasure As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHorReferenceDatCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHorReferenceDatCode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHorReferenceDatCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeographicComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGeographicComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hidLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidLatitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidLongitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorCollectionMetCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidHorCollectionMetDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorCollectionMetDesc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorReferenceDatCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidHorReferenceDatDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorReferenceDatDesc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidGeographicComment As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblSeparator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNamePrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNamePrefix As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrefix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbwPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbwPrefix As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''lblfirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfirstname As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblIndividualTitleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndividualTitleText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtIndividualTitleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIndividualTitleText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvIndividualTitleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvIndividualTitleText As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMailingAddressText_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressText_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressText_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressText_Contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvMailingAddressText_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressText_Contact As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSupplementalAddressText_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplementalAddressText_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSupplementalAddressText_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplementalAddressText_Contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbwSupplementalAddressText_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbwSupplementalAddressText_Contact As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''lblMailingAddressCityName_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressCityName_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressCityName_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressCityName_Contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvMailingAddressCityName_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressCityName_Contact As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMailingAddressStateCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressStateCode_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlContact_MailState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContact_MailState As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvMailingAddressStateCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressStateCode_Contact As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMailingAddressPostalCode_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailingAddressPostalCode_Contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvMailingAddressPostalCode_Contact As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rgxvMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgxvMailingAddressPostalCode_Contact As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''filtxtMailingAddressPostalCode_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtMailingAddressPostalCode_Contact As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''lblTelephoneNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNumberText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumberText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelephoneNumberText_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumberText_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvTelephoneNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvTelephoneNumberText As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblTelephoneExtensionNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneExtensionNumberText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneExtensionNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneExtensionNumberText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelephoneExtensionNumberText_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneExtensionNumberText_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''tbwTelephoneExtensionNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbwTelephoneExtensionNumberText As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''lblTelephoneNumberText_mobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNumberText_mobile As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneNumber_Mobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumber_Mobile As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelephoneNumber_Mobile_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumber_Mobile_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''lblTelephoneNumberText_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNumberText_fax As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTelephoneNumber_Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumber_Fax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelephoneNumber_Fax_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNumber_Fax_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''lblElectronicAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElectronicAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtElectronicAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtElectronicAddressText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvElectronicAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvElectronicAddressText As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rgxvElectronicAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgxvElectronicAddress As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblContactAddressComment_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactAddressComment_Contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAddressComment_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressComment_Contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNAICSCodeLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNAICSCodeLookup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbllookupNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllookupNAICSCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLookupNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLookupNAICSCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLookupNAICSCode_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLookupNAICSCode_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''lbllookupNAICSCodeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllookupNAICSCodeDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLookupNAICSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLookupNAICSDesc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearchNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchNAICS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNAICS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUseNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseNAICSCode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblNAICSMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNAICSMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSelectedNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedNAICSCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSelectedNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectedNAICSCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNAICS As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRowCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvwNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwNAICS As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMap As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnPopupDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPopupDisplay As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GMap As Global.Reimers.Google.Map.Map
    
    '''<summary>
    '''lblMapLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMapLat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMapLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapLat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvMapLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMapLat As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMapLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMapLon As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMapLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapLon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvMapLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMapLon As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnCloseMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseMap As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUseLatLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseLatLon As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbtnGetLatLon_ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnGetLatLon_ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender
End Class
