'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EIS_rp_operscp_edit
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''lblSeparatorNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparatorNoText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMessageTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageTop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSave1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSummary3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummary3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''sumvFugitive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumvFugitive As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''lblEISYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEISYear As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEISYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEISYear As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmissionUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmissionUnitID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEmissionsUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmissionsUnitID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmissionUnitDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmissionUnitDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtUnitDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblProcessID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcessID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProcessID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcessID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblProcessDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcessDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProcessDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcessDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSourceClassCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSourceClassCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSourceClassCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSourceClassCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSccDescLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSccDescLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSccDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSccDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProcessOperatingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcessOperatingDetails As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCalcParamType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalcParamType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCalcParamType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalcParamType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvCalcParamType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvCalcParamType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCalcParamValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalcParamValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCalcParamValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalcParamValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtCalcParamValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtCalcParamValue As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvCalcParamValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvCalcParamValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvCalcParamValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvCalcParamValue As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblCalcParamUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalcParamUoM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCalcParamUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalcParamUoM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvCalcParamUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvCalcParamUoM As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMaterialCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaterialCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlMaterialCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMaterialCode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRPComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRPComment_TextBoxWatermarkExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPComment_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender
    
    '''<summary>
    '''regexpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexpName As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAvgHoursPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvgHoursPerDay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAvgHoursPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAvgHoursPerDay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvAvgHoursPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvAvgHoursPerDay As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''filtxtAvgHoursPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtAvgHoursPerDay As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''rngvAvgHoursPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvAvgHoursPerDay As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblAvgDaysPerWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvgDaysPerWeek As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAvgDaysPerWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAvgDaysPerWeek As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtAvgDaysPerWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtAvgDaysPerWeek As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvAvgDaysPerWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvAvgDaysPerWeek As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvAvgDaysPerWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvAvgDaysPerWeek As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblAvgWeeksPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvgWeeksPerYear As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAvgWeeksPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAvgWeeksPerYear As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtAvgWeeksPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtAvgWeeksPerYear As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvAvgWeeksPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvAvgWeeksPerYear As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvAvgWeeksPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvAvgWeeksPerYear As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblActualHoursPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActualHoursPerYear As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtActualHoursPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActualHoursPerYear As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filxtxActualHoursPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filxtxActualHoursPerYear As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvActualHoursPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvActualHoursPerYear As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvActualHoursPerYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvActualHoursPerYear As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblSeasonalInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeasonalInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWinterPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWinterPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWinterPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWinterPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtWinterPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtWinterPct As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvWinterPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvWinterPct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvWinterPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvWinterPct As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblSpringPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpringPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSpringPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpringPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtSpringPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtSpringPct As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvSpringPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvSpringPct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvSpringPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvSpringPct As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblSummerPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummerPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSummerPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSummerPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtSummerPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtSummerPct As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvSummerPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvSummerPct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvSummerPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvSummerPct As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblFallPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFallPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFallPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFallPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtFallPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtFallPct As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvFallPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvFallPct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvFallPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvFallPct As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblTotalPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTotalPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSumSeasonalPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSumSeasonalPct As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblTotalSeasonValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalSeasonValidate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFuelBurning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelBurning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblFuelUsage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelUsage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFuelBurning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFuelBurning As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlFuelBurning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFuelBurning As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblHeatContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeatContent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtHeatContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeatContent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtHeatContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtHeatContent As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvHeatContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHeatContent As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rgxvHeatContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgxvHeatContent As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''rngvHeatContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvHeatContent As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblHeatContentNumUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeatContentNumUoM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlHeatContentNumUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHeatContentNumUoM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlHeatContentDenUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHeatContentDenUoM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvHeatContentDenUoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHeatContentDenUoM As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSulfurPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSulfurPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSulfurPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSulfurPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtSulfurPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtSulfurPct As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''cbxSulfurNegligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxSulfurNegligible As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''reqvSulfurPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvSulfurPct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvSulfurPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvSulfurPct As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblAshPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAshPct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAshPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAshPct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtAshPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtAshPct As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''cbxAshNegligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxAshNegligible As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''reqvAshPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvAshPct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rngvAshPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvAshPct As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnSave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummary As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpeDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDelete As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''lblMessageBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageBottom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirmDelete As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDeleteConfirm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDeleteConfirm2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummary2 As Global.System.Web.UI.WebControls.Button
End Class
