'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EIS_rp_summary
    
    '''<summary>
    '''lblRPSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPSummary As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvwReportingPeriodSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwReportingPeriodSummary As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblRPSummaryNoRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPSummaryNoRP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvwRPSummary_NoRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwRPSummary_NoRP As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PreventRePost1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreventRePost1 As Global.GECO.PreventRePost
End Class
