'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eis_stack_details
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''btnReturnToSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnToSummary As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblStackDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStackDetails As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAddStack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddStack_ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStack_ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''btnDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplicate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDuplicate_ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplicate_ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblReleasePointID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReleasePointID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtReleasePointID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReleasePointID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPTypeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPTypeCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPTypeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPTypeCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPStatusCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPStatusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPStatusCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPStackHeightMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPStackHeightMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPStackHeightMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPStackHeightMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPStackDiameterMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPStackDiameterMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPStackDiameterMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPStackDiameterMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPExitGasVelocityMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPExitGasVelocityMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPExitGasVelocityMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPExitGasVelocityMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPExitGasFlowRateMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPExitGasFlowRateMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPExitGasFlowRateMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPExitGasFlowRateMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPExitGasTemperatureMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPExitGasTemperatureMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPExitGasTemperatureMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPExitGasTemperatureMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPFenceLineDistanceMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPFenceLineDistanceMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPFenceLineDistanceMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPFenceLineDistanceMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRPComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRPComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRPComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastEISSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastEISSubmit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdated As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNoRPGeoCoordInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRPGeoCoordInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLatitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLatitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLongitudeMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLongitudeMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlLocationMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocationMap As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgGoogleStaticMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGoogleStaticMap As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''LblHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorCollectionMetCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorCollectionMetCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHorReferenceDatCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHorReferenceDatCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblGeographicComment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGeographicComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastEISSubmit_SGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEISSubmit_SGC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtlastEISSubmit_SGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastEISSubmit_SGC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLastUpdate_SGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate_SGC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastUpdate_SGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate_SGC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReleasePointAppMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReleasePointAppMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRPShutdownMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRPShutdownMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvwRPApportionment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwRPApportionment As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceRPApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRPApp As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblSeparatorOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeparatorOnly As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummary2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlPopUpAddStack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopUpAddStack As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewStackID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filtxtNewStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtxtNewStackID As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''reqvNewStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNewStackID As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cusvStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusvStackID As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''ddlRPTypeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRPTypeCode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''reqvRPtypeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvRPtypeCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtNewStackDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewStackDesc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvNewStackDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNewStackDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnInsertStack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertStack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelStack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelStack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDuplicate As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStackID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDupStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDupStackID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDupStackID_FilteredTextBoxExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDupStackID_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''cusvDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusvDuplicate As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''reqvDupStackID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvDupStackID As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblStackDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStackDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDupStackDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDupStackDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqvDupStackDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvDupStackDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDupInsertStack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDupInsertStack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelDupStack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelDupStack As Global.System.Web.UI.WebControls.Button
End Class
