'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Permit_Application
    
    '''<summary>
    '''lblAppNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tApplicationDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tApplicationDetails As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''pFeesNotApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pFeesNotApplicable As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pFeesNotDetermined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pFeesNotDetermined As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tblFeesSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFeesSummary As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''pnlGenerateInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGenerateInvoice As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hAppNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hAppNumber As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pGenerateInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pGenerateInvoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnGenerateInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerateInvoice As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pGenerateDbError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pGenerateDbError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pGenerateExists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pGenerateExists As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pGenerateNoItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pGenerateNoItems As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pGenerateSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pGenerateSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNewInvoiceNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewInvoiceNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlInvoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInvoices As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdInvoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdInvoices As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPayments As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPayments As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tFacilityInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tFacilityInfo As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''pNoContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNoContact As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tContact As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tTracking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tTracking As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.MainMaster
        Get
            Return CType(MyBase.Master,GECO.MainMaster)
        End Get
    End Property
End Class
