'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PermitDefault

    '''<summary>
    '''pNoOpenApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNoOpenApps As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdOpenApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdOpenApps As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pNoCurrentPermits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNoCurrentPermits As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pYesCurrentPermits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pYesCurrentPermits As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hlPermitSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPermitSearch As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''grdCurrentPermits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCurrentPermits As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pNoClosedApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNoClosedApps As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdClosedApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdClosedApps As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.MainLayout
        Get
            Return CType(MyBase.Master, GECO.MainLayout)
        End Get
    End Property
End Class
