'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Fees_Default
    
    '''<summary>
    '''lblFacilityDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilityDisplay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAIRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAIRS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pAnnualFees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAnnualFees As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdAnnualFees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAnnualFees As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pApplicationDeposits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pApplicationDeposits As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''grdApplicationDeposits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdApplicationDeposits As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.MainLayout
        Get
            Return CType(MyBase.Master,GECO.MainLayout)
        End Get
    End Property
End Class
