'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EIS_Facility_EditPage

    '''<summary>
    '''pnlFacilityEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFacilityEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lblFacilityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilityName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSiteAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqvFacilitySiteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvFacilitySiteDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNAICSCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNAICSCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnNAICSLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNAICSLookup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''reqvNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvNAICSCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rgxvNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgxvNAICSCode As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CustomValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator1 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblFacilitySiteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacilitySiteComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFacilitySiteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFacilitySiteComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator3 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lnkGoogleMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGoogleMap As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgGoogleStaticMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGoogleStaticMap As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pLatLonLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pLatLonLocked As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pGeoInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pGeoInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLatitudeMeasure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLatitudeMeasure As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGetLatLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetLatLon As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''reqvLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvLatitudeMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngvLatitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvLatitudeMeasure As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLongitudeMeasure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLongitudeMeasure As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqvLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvLongitudeMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngvLongitudeMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvLongitudeMeasure As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHorCollectionMetCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHorCollectionMetCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''reqvHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHorCollectionMetCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqvHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rngvHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rngvHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHorReferenceDatCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHorReferenceDatCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''reqvHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvHorReferenceDatCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeographicComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGeographicComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexpName As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''hidLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidLatitude As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidLongitude As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHorCollectionMetCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorCollectionMetCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHorCollectionMetDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorCollectionMetDesc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHorizontalAccuracyMeasure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorizontalAccuracyMeasure As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHorReferenceDatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorReferenceDatCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHorReferenceDatDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHorReferenceDatDesc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidGeographicComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidGeographicComment As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlNAICSCodeLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNAICSCodeLookup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbllookupNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllookupNAICSCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLookupNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLookupNAICSCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbllookupNAICSCodeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllookupNAICSCodeDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLookupNAICSDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLookupNAICSDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchNAICS As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNAICS As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pNaicsSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNaicsSelected As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSelectedNaicsCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedNaicsCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnUseNAICSCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseNAICSCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRowCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvwNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwNAICS As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMap As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnPopupDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPopupDisplay As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GMap As Global.Reimers.Google.Map.Map

    '''<summary>
    '''txtMapLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMapLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapLon As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUseLatLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseLatLon As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCloseMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseMap As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As GECO.EIS
        Get
            Return CType(MyBase.Master, GECO.EIS)
        End Get
    End Property
End Class
