-- Fees/FeeInvoice.rpt
SELECT FS_ADMIN.NUMFEEYEAR,
       FS_ADMIN.INTSUBMITTAL,
       FS_ADMIN.STRAIRSNUMBER,
       VW_FS_FEEINVOICE.INVOICEID,
       VW_FS_FEEINVOICE.NUMAMOUNT,
       VW_FS_FEEINVOICE.DUEDATE,
       VW_FS_FEEINVOICE.INVOICEDATE,
       VW_FS_FEEINVOICE.ACTIVE,
       VW_FS_FEEINVOICE.NUMTOTALFEE,
       VW_FS_FEEINVOICE.NUMFEEYEAR,
       FSLK_PAYTYPE.STRPAYTYPEDESC,
       VW_FS_FEEINVOICE.ADMINISTRATIVEFEE
FROM (VW_FS_FEEINVOICE AS VW_FS_FEEINVOICE
    INNER JOIN FS_ADMIN AS FS_ADMIN
    ON VW_FS_FEEINVOICE.STRAIRSNUMBER = FS_ADMIN.STRAIRSNUMBER
        AND VW_FS_FEEINVOICE.NUMFEEYEAR = FS_ADMIN.NUMFEEYEAR)
     INNER JOIN FSLK_PAYTYPE AS FSLK_PAYTYPE
                ON VW_FS_FEEINVOICE.STRPAYID = FSLK_PAYTYPE.NUMPAYTYPEID
WHERE VW_FS_FEEINVOICE.ACTIVE = '1';

SELECT INVOICEID,
       DATTRANSACTIONDATE,
       NUMPAYMENT,
       STRAIRSNUMBER,
       NUMFEEYEAR,
       STRCHECKNO,
       STRDEPOSITNO,
       ACTIVE
FROM FS_TRANSACTIONS
WHERE ACTIVE = '1'
