-- Fees/FeeInvoice.rpt
SELECT FS_ADMIN.NUMFEEYEAR
     , FS_ADMIN.INTSUBMITTAL
     , FS_ADMIN.STRAIRSNUMBER
     , VW_FS_FEEINVOICE.INVOICEID
     , VW_FS_FEEINVOICE.NUMAMOUNT
     , VW_FS_FEEINVOICE.DUEDATE
     , VW_FS_FEEINVOICE.INVOICEDATE
     , VW_FS_FEEINVOICE.ACTIVE
     , VW_FS_FEEINVOICE.NUMTOTALFEE
     , VW_FS_FEEINVOICE.NUMFEEYEAR
     , FSLK_PAYTYPE.STRPAYTYPEDESC
     , VW_FS_FEEINVOICE.ADMINISTRATIVEFEE
FROM   (AIRBRANCH.dbo.VW_FS_FEEINVOICE AS VW_FS_FEEINVOICE
INNER JOIN AIRBRANCH.dbo.FS_ADMIN AS FS_ADMIN
  ON VW_FS_FEEINVOICE.STRAIRSNUMBER = FS_ADMIN.STRAIRSNUMBER
     AND VW_FS_FEEINVOICE.NUMFEEYEAR = FS_ADMIN.NUMFEEYEAR)
INNER JOIN AIRBRANCH.dbo.FSLK_PAYTYPE AS FSLK_PAYTYPE
  ON VW_FS_FEEINVOICE.STRPAYID = FSLK_PAYTYPE.NUMPAYTYPEID
WHERE  VW_FS_FEEINVOICE.ACTIVE = '1';

-- Fees/FeeReport.rpt
SELECT FS_CONTACTINFO.STRCONTACTFIRSTNAME
     , FS_CONTACTINFO.STRCONTACTLASTNAME
     , FS_CONTACTINFO.STRCONTACTCOMPANYNAME
     , FS_CONTACTINFO.STRCONTACTADDRESS
     , FS_CONTACTINFO.STRCONTACTCITY
     , FS_CONTACTINFO.STRCONTACTSTATE
     , FS_CONTACTINFO.STRCONTACTZIPCODE
     , FS_FEEDATA.INTVOCTONS
     , FS_FEEDATA.INTPMTONS
     , FS_FEEDATA.INTSO2TONS
     , FS_FEEDATA.INTNOXTONS
     , FS_FEEDATA.STRNSPS
     , FS_FEEDATA.NUMTOTALFEE
     , FS_FEEDATA.STRCLASS
     , FS_MAILOUT.STRFIRSTNAME
     , FS_MAILOUT.STRLASTNAME
     , FS_MAILOUT.STRCONTACTCONAME
     , FS_MAILOUT.STRCONTACTADDRESS1
     , FS_MAILOUT.STRCONTACTCITY
     , FS_MAILOUT.STRCONTACTSTATE
     , FS_MAILOUT.STRCONTACTZIPCODE
     , FS_MAILOUT.STRFACILITYNAME
     , FS_MAILOUT.STRFACILITYADDRESS1
     , FS_MAILOUT.STRFACILITYCITY
     , FS_MAILOUT.STRFACILITYZIPCODE
     , FS_FEEDATA.NUMADMINFEE
     , FS_FEERATE.NUMPERTONRATE
     , FS_FEEDATA.STRNSPSEXEMPT
     , FS_FEEDATA.NUMSMFEE
     , FS_FEEDATA.NUMPART70FEE
     , FS_FEEDATA.NUMNSPSFEE
     , FS_FEEDATA.STRNSPSEXEMPTREASON
     , FS_FEEDATA.STROFFICIALNAME
     , FS_FEEDATA.STROFFICIALTITLE
     , FS_FEEDATA.STRPAYMENTPLAN
     , FS_FEEDATA.STRCOMMENT
     , FS_ADMIN.INTSUBMITTAL
     , FS_ADMIN.STRAIRSNUMBER
     , FS_ADMIN.NUMFEEYEAR
     , FS_ADMIN.UPDATEDATETIME
     , FS_FEERATE.NUMAATHRES
     , FS_FEERATE.NUMNATHRES
FROM   (((AIRBRANCH.dbo.FS_ADMIN AS FS_ADMIN
INNER JOIN AIRBRANCH.dbo.FS_FEERATE AS FS_FEERATE
  ON FS_ADMIN.NUMFEEYEAR = FS_FEERATE.NUMFEEYEAR)
LEFT OUTER JOIN AIRBRANCH.dbo.FS_MAILOUT AS FS_MAILOUT
  ON FS_ADMIN.NUMFEEYEAR = FS_MAILOUT.NUMFEEYEAR
     AND FS_ADMIN.STRAIRSNUMBER = FS_MAILOUT.STRAIRSNUMBER)
LEFT OUTER JOIN AIRBRANCH.dbo.FS_CONTACTINFO AS FS_CONTACTINFO
  ON FS_ADMIN.NUMFEEYEAR = FS_CONTACTINFO.NUMFEEYEAR
     AND FS_ADMIN.STRAIRSNUMBER = FS_CONTACTINFO.STRAIRSNUMBER)
LEFT OUTER JOIN AIRBRANCH.dbo.FS_FEEDATA AS FS_FEEDATA
  ON FS_ADMIN.STRAIRSNUMBER = FS_FEEDATA.STRAIRSNUMBER
     AND FS_ADMIN.NUMFEEYEAR = FS_FEEDATA.NUMFEEYEAR
WHERE  FS_ADMIN.NUMFEEYEAR > 2003
ORDER BY FS_ADMIN.NUMFEEYEAR DESC;
