name: .NET Unit Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  vs-test:
    # ↓ Change this to "false" to disable the workflow without any alert messages.
    if: ${{ false }}
    # ↑ Change to "true" (or delete) to enable the workflow.

    name: Run unit tests
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce

      - name: Create Web.configBuilder.Debug.xml file
        shell: powershell
        run: copy-item "GECO/Web.configBuilder.Server-sample.xml" "GECO/Web.configBuilder.Debug.xml"

      - name: Build and restore dependencies
        run: msbuild -t:restore,rebuild

      - name: Run vstests
        uses: microsoft/vstest-action@6ef4755ea07a3144e3da36f10d76187086eee5e6
        with:
          testAssembly: .\GECO.Test\bin\Debug\GECO.Test.dll
          runInParallel: true
