name: .NET Unit Tests

on:
  pull_request:

jobs:
  vs-test:
    # ↓ Change this to "false" to disable the workflow without any alert messages.
    if: ${{ true }}
    # ↑ Change to "true" (or delete) to enable the workflow.

    name: Run unit tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3
      - name: Create Web.configBuilder.Debug.xml file
        shell: powershell
        run: copy-item "GECO/Web.configBuilder.Server-sample.xml" "GECO/Web.configBuilder.Debug.xml"
      - name: Build and restore dependencies
        run: msbuild -t:restore,rebuild
      - name: Run vstests
        uses: microsoft/vstest-action@v1.0.0
        with:
          testAssembly: .\GECO.Test\bin\Debug\GECO.Test.dll
          runInParallel: true
